const UserActionTypes = {
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  LOGIN_EMAIL_START: 'LOGIN_EMAIL_START',
  LOGIN_GOOGLE_START: 'LOGIN_GOOGLE_START',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCEED: 'LOGIN_SUCCEED',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
  SIGN_OUT_SUCCEED: 'SIGN_OUT_SUCCEED'
}

export default UserActionTypes
