const UserActionTypes = {
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_EMAIL_START: 'SIGN_IN_EMAIL_START',
  SIGN_IN_GOOGLE_START: 'SIGN_IN_GOOGLE_START',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_IN_SUCCEED: 'SIGN_IN_SUCCEED',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  SIGN_UP_SUCCEED: 'SIGN_UP_SUCCEED',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
  SIGN_OUT_SUCCEED: 'SIGN_OUT_SUCCEED',
}

export default UserActionTypes
