const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
  CLEAR_CART: 'CLEAR_CART'
}

export default CartActionTypes
