const CatalogActionTypes = {
  FETCH_CATALOG_START: 'FETCH_CATALOG_START',
  FETCH_CATALOG_FAIL: 'FETCH_CATALOG_FAIL',
  FETCH_COLLECTION_SUCCEED: 'FETCH_COLLECTION_SUCCEED'
}

export default CatalogActionTypes
